trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: templates
      type: github
      name: neville-nazerane/Common-Pipelines
      endpoint: github.com_neville-nazerane

extends:
  template: Shared\netcore-ubuntu.yml@templates
  parameters:
    usePreRelease: false
    projectPath: src/Docs.Website/Server
    projectName: Docs.Website.Server
    destDirectory: /var/www/docs
    port: 5020

    service:
      description: Nuget documentations
      identifier: docs
      name: kestrel-docs
    configs:
      ASPNETCORE_ENVIRONMENT: Production
      connectionStrings__sqlDb: $(Secrets.Db)
    

