pool: hosted-linux

pr: none

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src

variables:
  projectPath: src/Docs.WebApp
  projectName: Docs.WebApp
  deploymentDestDirectory: /var/www/docs

stages:
  - stage: 
    displayName: Build Blazor
    jobs:

    - job: Compile
      steps:

      - script: |
          dotnet publish $(projectPath) -c release -o published
          mkdir -p compressed
          tar -czf compressed/$(projectName).tar.gz -C published .
        displayName: Publishing Website

      # - task: ArchiveFiles@2
      #   displayName: Compress before publish
      #   inputs:
      #     rootFolderOrFile: published
      #     includeRootFolder: false
      #     archiveFile: compressed/$(projectPath).zip
      #     verbose: true

      - publish: compressed
        displayName: Publish for release
        artifact: published

  - stage: CD
    displayName: Deploy to the VM

    jobs:
      - deployment: Deployment
        displayName: Deploy to Development VM
        environment:
          name: Development
          resourceType: VirtualMachine
          resourceName: websites
        strategy:
          runOnce:
            deploy:
              steps:

                - checkout: none

                # - script: ls

                - download: current
                  displayName: download published artifact
                  artifact: published

                - script: |
                    sudo rm -rf $(deploymentDestDirectory)
                    sudo mkdir -p $(deploymentDestDirectory)
                    sudo tar -xzf src/$(projectName).tar.gz -C $(deploymentDestDirectory)

                    rm -rf *
                  displayName: Unzipping website into destination folder
                  workingDirectory: $(Pipeline.Workspace)/published

      
                - task: DeleteFiles@1
                  displayName: Clean up
                              

# resources:
#   repositories:
#     - repository: templates
#       type: github
#       name: neville-nazerane/Common-Pipelines
#       endpoint: github.com_neville-nazerane

# extends:
#   template: Shared\netcore-ubuntu.yml@templates
#   parameters:
#     usePreRelease: false
#     projectPath: src/Docs.WebApp
#     projectName: Docs.WebApp
#     destDirectory: /var/www/docs
#     port: 5020

#     service:
#       description: Nuget documentations
#       identifier: docs
#       name: kestrel-docs
#     configs:
#       ASPNETCORE_ENVIRONMENT: Production
    

